version: 2
updates:
  -
    package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 4
    versioning-strategy: increase-if-necessary