services:
    waaz.dpd_plugin.form.type.dpd_shipping_gateway_classic:
        class: Waaz\SyliusDpdPlugin\Form\Type\ShippingGatewayClassicType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'dpd-classic', label: "DPD classic" }

    waaz.dpd_plugin.form.type.dpd_shipping_gateway_predict:
        class: Waaz\SyliusDpdPlugin\Form\Type\ShippingGatewayPredictType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'dpd-predict', label: "DPD predict" }

    waaz.dpd_plugin.form.type.dpd_shipping_gateway_relay:
        class: Waaz\SyliusDpdPlugin\Form\Type\ShippingGatewayRelayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'dpd-relay', label: "DPD relay" }

    waaz.dpd_plugin.api.shipping_label_fetcher:
        class: Waaz\SyliusDpdPlugin\Api\ShippingLabelFetcher
        arguments:
            - '@request_stack'
            - '@waaz.dpd_plugin.api.client'

    waaz.dpd_plugin.event_listener.dpd_shipping_export:
        class: Waaz\SyliusDpdPlugin\EventListener\ShippingExportEventListener
        arguments:
            - '@filesystem'
            - '@bitbag.repository.shipping_export'
            - '%bitbag.shipping_labels_path%'
            - '@waaz.dpd_plugin.api.shipping_label_fetcher'
        tags:
            - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }

    waaz.dpd_plugin.api.client:
        class: Waaz\SyliusDpdPlugin\Api\Client
        arguments:
            - '%waaz_sylius_dpd_plugin.weight_unit%'
            - '%waaz_sylius_dpd_plugin.sandbox%'
        
    waaz.dpd_plugin.api.pickup_point_client:
        class: Waaz\SyliusDpdPlugin\Api\PickupPointClient
        arguments:
            - '@http_client'
            - '%waaz_sylius_dpd_plugin.api_pickup_points_key%'

    waaz.dpd_plugin.provider.dpd:
        class: Waaz\SyliusDpdPlugin\Provider\DpdProvider
        arguments:
            - '@waaz.dpd_plugin.api.pickup_point_client'
        tags: 
            - { name: 'setono_sylius_pickup_point.provider', code: 'dpd-fr', label: 'DPD France' }